apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stg
  labels:
    app: nginx-stg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-stg
  template:
    metadata:
      labels:
        app: nginx-stg
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80